# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20170112_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Object',
        ),
    ]
