# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 17:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='name',
        ),
        migrations.AlterField(
            model_name='choice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
