# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20170112_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
